### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mahnouman**
Updating Master branch

### CODE REVIEW

**Comment by mahnouman** [comment]
Hello @DinisCruz please merge this, thanks

**Comment by mahnouman** [comment]
Not sure if I closed this by mistake, so just reopened.

**Comment by MariuszFerdyn** [comment]
It is AWS pipeline.

**Review by MariuszFerdyn — APPROVED** [review]
AWS

**Review by DinisCruz — APPROVED** [review]

**Pull request merged**
